import React, { useState } from 'react'
import PreMain from './PreMain'
import Main from './Main'
import Finish from './Finish';
import Header from './Header';


function index() {
  const [selected, setSelected] = useState(1)
  const [fin, setFin] = useState(false)

  const handleClickMain = (id) =>{
    if(id+1>3){
      setFin(true)
    }else{
      setSelected(id+1);
    }
    
  }

  const quiz = {
    id: 1,
    title: 'React Quiz',
    qes: [
      {
        id: 1,
        title: 'What is React?',
        links: [
          { id: 1, title: 'JavaScript library for building user interfaces' },
          { id: 2, title: 'Programming language' },
          { id: 3, title: 'Database management system' },
          { id: 4, title: 'Web browser' }
        ]
      },
      {
        id: 2,
        title: 'What is Next?',
        links: [
          { id: 1, title: 'Next library for building user interfaces' },
          { id: 2, title: 'Programming language' },
          { id: 3, title: 'Something other' },
          { id: 4, title: 'Web browser' }
        ]
      },
      {
        id: 3,
        title: 'What is JSX?',
        links: [
          { id: 1, title: 'A syntax extension for JavaScript' },
          { id: 2, title: 'A database query language' },
          { id: 3, title: 'A type of web server' },
          { id: 4, title: 'A CSS preprocessor' }
        ]
      },
      {
        id: 4,
        title: 'What is the virtual DOM?',
        links: [
          { id: 1, title: 'An in-memory representation of the real DOM elements generated by React components' },
          { id: 2, title: 'A type of database' },
          { id: 3, title: 'A front-end framework' },
          { id: 4, title: 'A style sheet language' }
        ]
      }
    ]
  };
  
  

  return (
    <>
      <div className=''>
          <Header/>
          <div className={`${fin ? 'flex' : 'hidden'} mt-16 w-full h-[70vh]  justify-center items-center`}>
            <Finish/>
          </div>
            
          <div className={`${fin && 'hidden'} max-w-[1200px] mx-auto mt-16`}>
              <PreMain content={quiz}/>
              {quiz.qes.map(qu=>(
                selected === qu.id ? <Main key={qu.id} content={qu} fu={handleClickMain} /> : null
              ))}
              
          </div>
      </div>
    </>
  )
}

export default index